backend:
  name: git-gateway
  branch: master
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "games"
    label: "Games"
    folder: "public/api/games.json"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "ID"
        name: "id"
        widget: "string"
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "URL"
        name: "url"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "string"
      - label: "Availability"
        name: "availability"
        widget: "object"
        fields:
          - label: "PC"
            name: "pc"
            widget: "boolean"
          - label: "Console"
            name: "console"
            widget: "boolean"
      - label: "Release date"
        name: "releaseDate"
        widget: "DateTime"
      - label: "Date added"
        name: "addedAt"
        widget: "DateTime"
  - name: "posts"
    label: "Posts"
    folder: "public/api/posts.json"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "URL"
        name: "url"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "string"
      - label: "Published date"
        name: "publishedAt"
        widget: "DateTime"
