name: Scrap games list from xbox.com
on:
  schedule:
    - cron: "0 9 * * *"
jobs:
  scrapGames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn --cwd ./packages/scrapper scrapGames
      - uses: peter-evans/create-pull-request@v3
        with:
          reviewers: zhouzi
