name: Scrap data from various sources
on:
  schedule:
    - cron: "0 9 * * *"
jobs:
  scrapGames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run scrapGames
      - run: npm run scrapNews
      - run: npm run generateRSS
      - uses: peter-evans/create-pull-request@v3
