name: Send newsletter
on:
  schedule:
    - cron: "0 9 * * THU"
jobs:
  sendNewsletter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run sendNewsletter
        env:
          SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
          SENDINBLUE_LIST_ID: ${{ secrets.SENDINBLUE_LIST_ID }}
      - uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
